### ISSUE TITLE
Thank you very much for sharing

### ISSUE THREAD

**Issue by huang229** [CoinCheung/BiSeNet#35] opened 2019-11-28 09:14 UTC
Thank you very much for sharing. ARM and FFM are not completely implemented according to the original author's requirements. Do you know if I feel right? You add your own ideas to this part of the implementation.

**Comment by huang229** [comment] 2019-11-28 09:29
I didn't find the detailed implementation of this module in the paper.    
def forward(self, x):
        H0, W0 = x.size()[2:]
        feat8, feat16, feat32 = self.resnet(x)
        H8, W8 = feat8.size()[2:]
        H16, W16 = feat16.size()[2:]
        H32, W32 = feat32.size()[2:]

        avg = F.avg_pool2d(feat32, feat32.size()[2:])
        avg = self.conv_avg(avg)
        avg_up = F.interpolate(avg, (H32, W32), mode='nearest')

        feat32_arm = self.arm32(feat32)
        feat32_sum = feat32_arm + avg_up
        feat32_up = F.interpolate(feat32_sum, (H16, W16), mode='nearest')
        feat32_up = self.conv_head32(feat32_up)

        feat16_arm = self.arm16(feat16)
        feat16_sum = feat16_arm + feat32_up
        feat16_up = F.interpolate(feat16_sum, (H8, W8), mode='nearest')
        feat16_up = self.conv_head16(feat16_up)

        return feat16_up, feat32_up # x8, x16

**Comment by CoinCheung** [comment] 2019-11-29 04:52
This is the ushape context branch. It is denoted in the picture of the paper.

**Comment by huang229** [comment] 2019-11-29 04:58
Thank you. As I saw later, there is a small white box at the bottom of figure 2a.
 Finally, we combine the up-sampled output feature of global pooling and the features of the lightweight model. This sentence is also understood.

**Comment by CoinCheung** [comment] 2019-11-30 13:32
Seems that the problem is solved, I am closing this.

**Closed by CoinCheung** 2019-11-30 13:32 UTC
