### ISSUE TITLE
A question about test mIoU

### ISSUE THREAD

**Issue by qifengluo** [CoinCheung/BiSeNet#141] opened 2021-03-12 01:53 UTC
hi，thanks for you share. I used the code to train bisenetv2, the train set and val set for train , and the test set for evaluation, but the test mIoU is very low, just 0.5, that's why?

**Comment by CoinCheung** [comment] 2021-05-23 10:19
How did you test it, and what is the test set like ?

**Comment by CoinCheung** [comment] 2021-07-01 11:59
Closing this because this is not active anymore and the problem is likely to be solved.

**Closed by CoinCheung** 2021-07-01 11:59 UTC
