### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by fancyhhhhhh** [CoinCheung/BiSeNet#281] opened 2022-12-02 05:58 UTC
Hi,I met the same problem 

![screenshot](https://user-images.githubusercontent.com/116441063/205225248-5e3bc5f9-a5e3-47e5-8347-842475f1bb16.png)

**Comment by CoinCheung** [comment] 2022-12-02 06:07
I tried again, and it works. What is your platform like, cmake version, cuda version? And better step of reproducing this?

**Comment by fancyhhhhhh** [comment] 2022-12-02 06:10
My platform is all the same as you,ubuntu18.04 cuda11.3 cmake 3.17.1 
the whole error information like this
![1](https://user-images.githubusercontent.com/116441063/205226886-e4956812-8cf0-40f9-b802-461755ebe733.png)
![2](https://user-images.githubusercontent.com/116441063/205226931-3b3241be-a26d-4106-b981-2dd1722b0d04.png)

**Comment by CoinCheung** [comment] 2022-12-02 06:17
Would you try this cmake version?
![image](https://user-images.githubusercontent.com/22693362/205228016-7cdeab73-9854-4e9a-8b97-90d397792745.png)

**Comment by fancyhhhhhh** [comment] 2022-12-02 06:18
The cuda version of my base environment is 11.7,but the cuda version of my conda environment(bisenetv2) is 11.3.
So could it be my environment? 
I am going to try 3.22.0-rc3,now

**Comment by fancyhhhhhh** [comment] 2022-12-02 06:30
Really really appreciate your patient and helpful assistance
It works,thank you so much
have a good day

**Comment by fancyhhhhhh** [comment] 2022-12-02 06:39
I got the result, fps = 131.051,and my GPU is NVIDIA RTX5000 
Thank you so much

**Comment by CoinCheung** [comment] 2022-12-02 06:42
Good to know you made it work,  I will make a bit update of the readme.

**Comment by CoinCheung** [comment] 2022-12-02 06:43
I am closing this since problem is solved.

**Closed by CoinCheung** 2022-12-02 06:43 UTC
