### ISSUE TITLE
why inference so slow (bisenetv2)?

### ISSUE THREAD

**Issue by vraivon** [CoinCheung/BiSeNet#62] opened 2020-06-04 02:39 UTC
According to paper, for a 2048*1024 input, bisenetv2 can inference at a  speed of 156FPS on GTX1080ti. But the inference speed for this repo is only 33FPS under the some conditions and removing booster branch .

**Comment by raijinspecial** [comment] 2020-06-14 19:12
I am also not able to reproduce the high FPS mentioned in the paper, how are you removing the booster layers from this code?

**Comment by CoinCheung** [comment] 2020-06-16 07:39
That is because, in the paper, they used tensorrt to optimize their model and run inference in deployment environment, but my code is only implemented in python.

**Comment by vraivon** [comment] 2020-06-17 09:35
> I am also not able to reproduce the high FPS mentioned in the paper, how are you removing the booster layers from this code?

just modify model while doing inference according to the paper.


> That is because, in the paper, they used tensorrt to optimize their model and run inference in deployment environment, but my code is only implemented in python.

I have deployed several different nets with tensorRT,  there are indeed some acceleration effects even without fp16 or int8 mode, but they have not achieved such a high acceleration (almost x5 compared to pytorch version).

**Comment by Yuyn1234** [comment] 2020-07-03 08:35
> According to paper, for a 2048*1024 input, bisenetv2 can inference at a speed of 156FPS on GTX1080ti. But the inference speed for this repo is only 33FPS under the some conditions and removing booster branch .

The paper claimed that the  input images were resized to 1024*512 and finally unsampled to 2048*1024 for evaluation during the inference. Maybe it is the matter.

**Comment by umairanis03** [comment] 2020-07-08 13:51
Hi @vraivon @raijinspecial 

I am unable to access the pre-trained model using pan Baidu. Can you please provide me it's google drive link or can mail it to anis.1@iitj.ac.in

**Comment by CoinCheung** [comment] 2020-09-29 06:52
Hi, 

I updated specification of speed, and how I tested it. I am closing this, but you can still discuss here.

**Closed by CoinCheung** 2020-09-29 06:52 UTC
