### ISSUE TITLE
 cpu占用率70%，是正常吗 cpu占用率70%，是正常吗 Is the CPU usage 70% normal？？？？？

### ISSUE THREAD

**Issue by zhuya1996** [CoinCheung/BiSeNet#231] opened 2022-04-21 03:18 UTC

**Comment by CoinCheung** [comment] 2022-04-23 12:06
Yes it is normal, if you use augmentations, cpu usage would raise.

**Comment by zhuya1996** [comment] 2022-04-28 05:35
> 是的，这是正常的，如果你使用增强，cpu 使用率会增加。

如何降低cpu占用率 有啥办法吗，而且还都用gpu ，cpu还这么高

**Comment by zhuya1996** [comment] 2022-04-28 05:49
可以加个vx 吗 都是中国人  您写的这个特别好，我项目想用您这个，就是cpu占用率高，我想解决这个问题可以吗 有偿

**Comment by CoinCheung** [comment] 2022-04-28 10:57
Are you training or running inference? What is the version of your pytorch?

If you are training, please set these environment variable, and see if cpu occupation has dropped.

**Comment by zhuya1996** [comment] 2022-04-29 01:29
我在推理的时候，cpu占用到了70-90%，pytorch的版本是1.7.1 还有一个pytorch1.8  都是一样的

**Comment by CoinCheung** [comment] 2022-04-29 03:02
Would you please post a piece of sample code, such that I can debug locally?

**Comment by zhuya1996** [comment] 2022-04-29 03:15
我发送了，您那边能收到嘛



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CoinCheung/BiSeNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月29日(星期五) 中午11:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CoinCheung/BiSeNet]  cpu占用率70%，是正常吗 cpu占用率70%，是正常吗 Is the CPU usage 70% normal？？？？？ (Issue #231)





 
Would you please post a piece of sample code, such that I can debug locally?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

BiSeNet-master2.rar (263.38M, 2022年05月29日 11:12 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=2d646661c5ecbedd3a18c7301631051d035607560908025648525351021c035303544b5800080f1f555554055507035604060302302237700c37032f55451a5f04171204420319400416665c&t=exs_ftn_download&code=edfa0172

**Comment by CoinCheung** [comment] 2022-04-29 03:21
I am afraid not, would you please send here: coin.cheung@gmail.com

**Comment by zhuya1996** [comment] 2022-04-29 03:31
我重新发送了 您再看看

**Comment by CoinCheung** [comment] 2022-04-29 04:06
You gave me a whole codebase. Would you please narrow down the location of the problem? Would you tell me how did you reproduce the problem? Which script are you running?

**Comment by CoinCheung** [comment] 2022-04-29 04:15
If you are running `app2.py`, be aware that pre-processes and post-processes are implemented on cpu. You can move them to gpu like this:
![图片](https://user-images.githubusercontent.com/22693362/165884295-485355ce-974e-41f8-a979-9a5abd7b3d8b.png)

I did not debug this locally so there might be errors in this **example**, you can debug it yourself and see if cpu usage will drop.

**Comment by zhuya1996** [comment] 2022-04-29 05:09
我启动main.py&nbsp; cpu 占用率很高，我想降低cpu的占用率




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月29日(星期五) 中午12:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CoinCheung/BiSeNet]  cpu占用率70%，是正常吗 cpu占用率70%，是正常吗 Is the CPU usage 70% normal？？？？？ (Issue #231)






你给了我一个完整的代码库。请你缩小问题的范围好吗？你能告诉我你是如何重现这个问题的吗？你用的是哪个脚本？

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
您收到这个消息是因为您编写了这个线程。留言 ID ***@***.*** gave me a whole codebase. Would you please narrow down the location of the problem? Would you tell me how did you reproduce the problem? Which script are you running?.—

**Comment by zhuya1996** [comment] 2022-04-29 05:31
您图中的im=F.interpolate    这个F 是指什么呢

**Comment by zhuya1996** [comment] 2022-04-30 14:52
您可以帮帮我嘛   谢谢您

**Comment by zhuya1996** [comment] 2022-04-30 14:52
您可以帮帮我吗

**Comment by zhuya1996** [comment] 2022-04-30 15:15
用了您上面的代码，cpu还是一样， 您能帮我调试下吗

**Comment by CoinCheung** [comment] 2022-05-01 03:39
Have you tried to move pre-process and post-process to gpu? The code in the picture still works on cpu, but you can change to gpu mode by calling `.cuda()` at the end of the first 4 lines.

**Comment by zhuya1996** [comment] 2022-05-02 04:18
我不会移动到gpu ，您能帮帮我嘛 我付费

**Comment by zhuya1996** [comment] 2022-05-02 04:36
您好，可以帮帮我吗

**Comment by CoinCheung** [comment] 2022-05-02 04:37
Something like this:
![图片](https://user-images.githubusercontent.com/22693362/166184973-41310cc8-8c4d-42a5-a2f2-09793ae68af6.png)

**Comment by zhuya1996** [comment] 2022-05-02 05:47
我照您的代码做了 在cpu 在23% 左右， 使用了gpu 还有这么高吗  一秒检测4张图 左右的

**Comment by CoinCheung** [comment] 2022-05-02 06:23
You can also move the following line to gpu:
![图片](https://user-images.githubusercontent.com/22693362/166192858-3d3152a8-5f5d-46cb-9b56-9aaa8d257b6a.png)

Remove this, and use code like this:
![图片](https://user-images.githubusercontent.com/22693362/166192931-9378f45f-4b2d-490a-b03b-e0778206769b.png)


Besides, you can move these 3 lines to `__init__`, such that you do not need to initialize them each time you call the function:
![图片](https://user-images.githubusercontent.com/22693362/166192991-3277f945-9481-4b94-b610-478dd049a3de.png)

**Comment by zhuya1996** [comment] 2022-05-02 06:44
![U9LEJSXK8$AG~389LUV)OZQ](https://user-images.githubusercontent.com/25482513/166194791-70809928-396f-42a4-9b4b-1576ff49e2dd.png)

**Comment by zhuya1996** [comment] 2022-05-02 06:54
是这样嘛，但是cpu 刚开始高，后面降低了，这个原因是什么呢

**Comment by zhuya1996** [comment] 2022-05-02 06:54
![T@4KX%}Z$0 {VD~HJSZBS@O](https://user-images.githubusercontent.com/25482513/166195805-cbbf3d70-5fc0-4178-b3c7-c9654c0a461c.png)
![B6MH@ZK8SR2GVBSN_19_6(4](https://user-images.githubusercontent.com/25482513/166195807-d7d3431d-2555-4caf-a1c4-0524881a4c13.png)

**Comment by zhuya1996** [comment] 2022-05-02 07:28
还是哪里有问题，cpu 还是到50%了

**Comment by zhuya1996** [comment] 2022-05-02 11:33
能加您个qq  请教您吗

**Comment by CoinCheung** [comment] 2022-05-02 11:41
These two lines are useless since we have implemented it with pytorch, you can remove them:
![图片](https://user-images.githubusercontent.com/22693362/166228088-698eada9-f122-4456-bfc6-71a0feb64f17.png)

**Comment by zhuya1996** [comment] 2022-05-02 12:01
![52G`TY9%W{ V $J~AEU@9IM](https://user-images.githubusercontent.com/25482513/166230420-cf96eaaf-e07d-438f-a914-b80b8589a504.png)
![1V}GA3D97D2A3EDBEKB 1E7](https://user-images.githubusercontent.com/25482513/166230428-de66da49-e3b1-4d6e-9dbc-551c54367ab6.png)

**Comment by zhuya1996** [comment] 2022-05-02 12:02
您好 ，还是这么高的cpu

**Comment by CoinCheung** [comment] 2022-05-02 12:08
Then I have no idea what causes this :(. Have you tried to comment out the related part of this project, and see the cpu usage of the inference-free code?

Besides, why do you resize the frame here?
![图片](https://user-images.githubusercontent.com/22693362/166230954-b18cafd0-3358-41e2-8a54-5f182f787633.png)
Maybe you can set the frame size with `cv2.VideoCapture` directly.

**Comment by CoinCheung** [comment] 2022-05-09 12:18
Glad to know that you have figured it out. I will add a bit specification about this some time in the future. 

Thanks for sharing this !!!

**Comment by CoinCheung** [comment] 2022-05-09 12:18
I am closing this since problem is solved.

**Closed by CoinCheung** 2022-05-09 12:18 UTC
