### ISSUE TITLE
Training errow

### ISSUE THREAD

**Issue by Jasonshao0123** [CoinCheung/BiSeNet#259] opened 2022-08-22 04:29 UTC
![2a7bd65854f0a80d585a76f7e410bc2](https://user-images.githubusercontent.com/46207106/185839605-e49c1b89-99ae-4490-a5c6-5f625ff76b22.png)
How to solve this problem？

**Comment by CoinCheung** [comment] 2022-08-23 12:48
Please follow the step of readme to launch training, and please use same version of pytorch.

**Comment by Jasonshao0123** [comment] 2022-08-24 08:14
Thanks for your reply，
I didn't change the version of pytorch.
I add this code into train_amp.py and the problem was solved.
parse.add_argument('--local_rank', defautle=-1, type=int,
                                   help='node rank for distributed training')

**Comment by CoinCheung** [comment] 2022-11-15 03:24
I am closing this, since the problem is solved.

**Closed by CoinCheung** 2022-11-15 03:24 UTC
