### ISSUE TITLE
use for kitti, how to train or finetune,thanks!

### ISSUE THREAD

**Issue by emilyemliyM** [CoinCheung/BiSeNet#257] opened 2022-08-19 14:30 UTC
Dear author,

If I want to use the model to do the training in the Kitti dataset.
So we have the different category number, for the sityscapes ,it is 20 .
For Kitti, for examplt, the category number is 6.
So how to o the training work? add a conv2d(20, 6)? or anything else.

**Comment by emilyemliyM** [comment] 2022-08-19 15:14
I use the command below:L
torchrun --nproc_per_node=2 train_amp.py --finetune-from pretrain_weight/model_final_v2_city.pth

But it shows that missing a lot of key : below:
![image](https://user-images.githubusercontent.com/88700988/185650743-36fefb3d-9468-4d0d-8b6b-b41cfc56ecda.png)


I just set the category num to 5.

**Comment by CoinCheung** [comment] 2022-08-23 12:49
Maybe you are using unmatched config file and finetune weight file.

**Comment by CoinCheung** [comment] 2022-11-15 03:25
Close this, since this is not activate for long time, and likely the problem is solved.

**Closed by CoinCheung** 2022-11-15 03:25 UTC
