### ISSUE TITLE
单卡单机训练时出现报错

### ISSUE THREAD

**Issue by AD122583SD** [CoinCheung/BiSeNet#290] opened 2023-02-14 13:08 UTC
单卡单机训练时
python -m torch.distributed.launch --nproc_per_node=1 tools/train_amp.py --config configs/bisenetv2_city.py

出现报错
usage: train_amp.py [-h] [--config CONFIG] [--finetune-from FINETUNE_FROM]
train_amp.py: error: unrecognized arguments: --local_rank=0
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 24379) of binary: /home/cby/anaconda3/envs/bisenet/bin/python
请问有什么办法解决吗

**Comment by CoinCheung** [comment] 2023-02-15 02:20
Try this: 
```
torchrun--nproc_per_node=1 tools/train_amp.py --config configs/bisenetv2_city.py
```

**Comment by AtaraxyAdong** [comment] 2023-02-15 11:22
Hello.  I have a similar problem when training on a single machine with a single card, 
but when I run `torchrun --nproc_per_node=1 tools/train_amp.py --config configs/bisenetv2_city.py`, it reports an error of `failed to create process.`.
I've searched for a solution, but it didn't work. I would like to ask if there is any solution to this problem.

**Comment by AD122583SD** [comment] 2023-02-16 00:37
Thank  you very much for your guidance and help. I haven't been able to solve  this problem yet. I will continue to pay attention to this problem and  try to solve it      




趋离i
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CoinCheung/BiSeNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月15日(星期三) 晚上7:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CoinCheung/BiSeNet] 单卡单机训练时出现报错 (Issue #290)





 
Hello.  I have a similar problem when training on a single machine with a single card,
 but when I run torchrun --nproc_per_node=1 tools/train_amp.py --config configs/bisenetv2_city.py, it reports an error of failed to create process..
 I've searched for a solution, but it didn't work. I would like to ask if there is any solution to this problem.

**Comment by CoinCheung** [comment] 2023-02-16 11:05
@AtaraxyAdong @AD122583SD  What is your platform like please? How did you launch training ? What is the error message like?

Please add CUDA_VISIBLE_DEVICES=0 if your machine has more than one gpus.

**Comment by AtaraxyAdong** [comment] 2023-02-17 05:03
@CoinCheung Thanks for your advice, I solved this problem.
The error message was only `failed to create process`. Later, I realized that the video memory of my machine was too small. After I changed to a machine with a larger video memory, it could run normally.

**Comment by anizyu** [comment] 2023-05-15 02:44
单卡单机训练时
export CUDA_VISIBLE_DEVICES=0 
torchrun --nproc_per_node=1 tools/train_amp.py --config configs/bisenetv2_city.py
出现报错
Traceback (most recent call last):
  File "tools/train_amp.py", line 268, in <module>
    main()
  File "tools/train_amp.py", line 264, in main
    train()
  File "tools/train_amp.py", line 193, in train
    optim = set_optimizer(net)
  File "tools/train_amp.py", line 70, in set_optimizer
    wd_params, nowd_params, lr_mul_wd_params, lr_mul_nowd_params = model.get_params(),
ValueError: not enough values to unpack (expected 4, got 1)
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 6160) of binary: /home/zy/miniconda3/envs/bise/bin/python
Traceback (most recent call last):
  File "/home/zy/miniconda3/envs/bise/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/zy/miniconda3/envs/bise/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/zy/miniconda3/envs/bise/lib/python3.8/site-packages/torch/distributed/run.py", line 724, in main
    run(args)
  File "/home/zy/miniconda3/envs/bise/lib/python3.8/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/home/zy/miniconda3/envs/bise/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/zy/miniconda3/envs/bise/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/train_amp.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-05-15_10:31:29
  host      : com
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 6160)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

请问有什么办法解决吗?

**Comment by CoinCheung** [comment] 2023-06-08 06:58
Sorry for being so late. Have your solved this problem?

**Comment by AD122583SD** [comment] 2023-06-09 07:40
Sorry, this question has not been addressed




趋离i
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CoinCheung/BiSeNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月8日(星期四) 下午2:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CoinCheung/BiSeNet] 单卡单机训练时出现报错 (Issue #290)





 
Sorry for being so late. Have your solved this problem?

**Comment by CoinCheung** [comment] 2023-06-09 08:15
Then what is your platform like? And what modifications did you made to the original code?

**Comment by YyChen818** [comment] 2023-07-18 09:21
I have the same problem with you. May I ask that did you solve it and how？Hope you reply， thanks！

**Comment by CoinCheung** [comment] 2023-08-07 10:42
I am closing this, since no more information is provided, maybe this is no longer a problem now.

**Closed by CoinCheung** 2023-08-07 10:42 UTC
