### ISSUE TITLE
onnx to tensorrt : Assertion failed: scales.is_weights() && "Resize scales must be an initializer!"

### ISSUE THREAD

**Issue by yuzhj** [CoinCheung/BiSeNet#262] opened 2022-09-06 02:08 UTC
Here is the error log
![image](https://user-images.githubusercontent.com/31239926/188531441-de73e104-6de8-461e-aa23-8be6ffa23927.png)
Here is my environment
cuda 11.6
TensorRT 8.2.3.0
ONNX 1.12
ONNXRuntime 1.8.1
Do you have any advice? Thanks in advance

**Comment by CoinCheung** [comment] 2022-09-06 02:25
What are the steps to reproduce this error?

**Comment by yuzhj** [comment] 2022-09-06 02:51
> 
step 1
```bash
python tools/export_onnx.py --config configs/bisenetv1_coco.py --weight-path pretrained/coco_stuff/model_final_v1_coco_new.pth --outpath ./model_v1.onnx
```
step 2
```bash
./tensorrt/build/segment compile model_v1.onnx model_v1.trt
```
I faced this error when I convert the model from onnx to trt

**Comment by CoinCheung** [comment] 2022-09-06 02:58
Maybe switch to tensorrt 8.2.5 and try again? Or use cuda 11.3?

**Comment by yuzhj** [comment] 2022-09-06 03:17
> Maybe switch to tensorrt 8.2.5 and try again? Or use cuda 11.3?

same error on tensorrt 8.2.5 and cuda 11.3

**Comment by CoinCheung** [comment] 2022-09-06 03:31
That is weird, it works on my platform. Did you make any changes to the code? Would you please align the cudnn version as mine and try again?

**Comment by CoinCheung** [comment] 2022-11-15 03:23
I am closing this, since this is not activate for a long time. Never mind, you can still open new issues, if you would like.

**Closed by CoinCheung** 2022-11-15 03:23 UTC
