### ISSUE TITLE
about the test of FPS and segmentation image

### ISSUE THREAD

**Issue by quminjie** [CoinCheung/BiSeNet#300] opened 2023-04-11 09:47 UTC
I failed to test FPS using C++ code. May I ask if you are using Python code to implement FPS testing? Could you share the code? Thank you for sharing.
In addition, I trained Bisenetv2 using Cityscapes acheive the same miou as the author. I would like to ask if there are any color errors in the resulting image after segmentation using the final model, and the generated segmentation image is not very effective.

**Comment by CoinCheung** [comment] 2023-04-13 07:32
Hi,

To be honest, I do not have such python script for testing the speed with tensorrt. Maybe I will add this in the future but not in short future...

The color is generated randomly, not following the original cityscapes colormap, so it does not match the pictures you see in the paper.

**Comment by quminjie** [comment] 2023-04-13 07:42
catkin-tools and catkin-pkg have been installed in my environment. But when i use cmake..，it still get an error saying "no module of 'catkin'"


Have you ever encountered this problem？





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CoinCheung/BiSeNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月13日(星期四) 下午3:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CoinCheung/BiSeNet] about the test of FPS and segmentation image (Issue #300)





 
Hi,
 
To be honest, I do not have such python script for testing the speed with tensorrt. Maybe I will add this in the future but not in short future...
 
The color is generated randomly, not following the original cityscapes colormap, so it does not match the pictures you see in the paper.

**Comment by CoinCheung** [comment] 2023-04-13 08:26
Would you tell me the steps how to reproduce this problem?

**Comment by CoinCheung** [comment] 2023-04-13 08:41
What is your platform like? Is it same as my platform?

**Comment by quminjie** [comment] 2023-04-13 09:07
可能是cmake环境的问题，我再继续调试一下。谢谢您的回复！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CoinCheung/BiSeNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月13日(星期四) 下午4:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CoinCheung/BiSeNet] about the test of FPS and segmentation image (Issue #300)





 
What is your platform like? Is it same as my platform?

**Comment by WenwenZong** [comment] 2023-04-25 00:56
> I failed to test FPS using C++ code. May I ask if you are using Python code to implement FPS testing? Could you share the code? Thank you for sharing. In addition, I trained Bisenetv2 using Cityscapes acheive the same miou as the author. I would like to ask if there are any color errors in the resulting image after segmentation using the final model, and the generated segmentation image is not very effective.
> 
> 我未能使用C++代码测试 FPS。请问您是否正在使用 Python 代码来实现 FPS 测试？你能分享代码吗？谢谢你的分享。此外，我使用城市景观训练了Bisenetv2，实现了与作者相同的miou。我想问一下使用最终模型分割后生成的图像是否存在任何颜色错误，并且生成的分割图像不是很有效。

Hello, when I reproduce the code, there may be some fluctuations, and the maximum miou is equal to 73.1%. I saw that you reproduced the same result. Could you please add your contact information and provide me with some information about your training so that I can better reproduce the code? thank you.

**Comment by quminjie** [comment] 2023-04-25 02:29
My parameter settings are the same as the author, and the reproduction result is less than a point different from the author, the highest is 76.6%, and the result may be different because of the GPU.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CoinCheung/BiSeNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月25日(星期二) 上午8:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CoinCheung/BiSeNet] about the test of FPS and segmentation image (Issue #300)





  
I failed to test FPS using C++ code. May I ask if you are using Python code to implement FPS testing? Could you share the code? Thank you for sharing. In addition, I trained Bisenetv2 using Cityscapes acheive the same miou as the author. I would like to ask if there are any color errors in the resulting image after segmentation using the final model, and the generated segmentation image is not very effective.
 
我未能使用C++代码测试 FPS。请问您是否正在使用 Python 代码来实现 FPS 测试？你能分享代码吗？谢谢你的分享。此外，我使用城市景观训练了Bisenetv2，实现了与作者相同的miou。我想问一下使用最终模型分割后生成的图像是否存在任何颜色错误，并且生成的分割图像不是很有效。
  
Hello, when I reproduce the code, there may be some fluctuations, and the maximum miou is equal to 73.1%. I saw that you reproduced the same result. Could you please add your contact information and provide me with some information about your training so that I can better reproduce the code? thank you.

**Comment by WenwenZong** [comment] 2023-05-05 02:46
Firstly, thank you very much for your reply. What kind of GPU are you using and how many cards are used for training? What is the approximate range of fluctuation between the maximum and minimum values during your multiple training sessions? Finally, thank you again. If you have time, please reply as soon as possible.

**Comment by quminjie** [comment] 2023-05-05 08:05
I used single card 3090.The minimum values is 74.2% and the maximum is 76.6
%.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CoinCheung/BiSeNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月5日(星期五) 上午10:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CoinCheung/BiSeNet] about the test of FPS and segmentation image (Issue #300)





 
Firstly, thank you very much for your reply. What kind of GPU are you using and how many cards are used for training? What is the approximate range of fluctuation between the maximum and minimum values during your multiple training sessions? Finally, thank you again. If you have time, please reply as soon as possible.

**Comment by WenwenZong** [comment] 2023-05-06 00:58
请问你设置的batchsize是16吗?我使用的卡与你的相同，麻烦能告诉我你在训练的时候是将多卡训练改为单卡了，还是在训练的命令中设置的？具体的我给您发了个邮件，麻烦您有空的时候能进行回复。万分感谢。

**Comment by WenwenZong** [comment] 2023-05-16 08:39
> I used single card 3090.The minimum values is 74.2% and the maximum is 76.6 %.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "CoinCheung/BiSeNet" ***@***.***&gt;; 发送时间:&nbsp;2023年5月5日(星期五) 上午10:46 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [CoinCheung/BiSeNet] about the test of FPS and segmentation image (Issue #300) Firstly, thank you very much for your reply. What kind of GPU are you using and how many cards are used for training? What is the approximate range of fluctuation between the maximum and minimum values during your multiple training sessions? Finally, thank you again. If you have time, please reply as soon as possible. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

请问你的batchsize是设置的多少，能麻烦回复下吗？以及你单卡训练时train_amp.py是怎么修改的？

**Comment by WenwenZong** [comment] 2023-05-24 01:17
> My parameter settings are the same as the author, and the reproduction result is less than a point different from the author, the highest is 76.6%, and the result may be different because of the GPU.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "CoinCheung/BiSeNet" ***@***.***&gt;; 发送时间:&nbsp;2023年4月25日(星期二) 上午8:56 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [CoinCheung/BiSeNet] about the test of FPS and segmentation image (Issue #300) I failed to test FPS using C++ code. May I ask if you are using Python code to implement FPS testing? Could you share the code? Thank you for sharing. In addition, I trained Bisenetv2 using Cityscapes acheive the same miou as the author. I would like to ask if there are any color errors in the resulting image after segmentation using the final model, and the generated segmentation image is not very effective. 我未能使用C++代码测试 FPS。请问您是否正在使用 Python 代码来实现 FPS 测试？你能分享代码吗？谢谢你的分享。此外，我使用城市景观训练了Bisenetv2，实现了与作者相同的miou。我想问一下使用最终模型分割后生成的图像是否存在任何颜色错误，并且生成的分割图像不是很有效。 Hello, when I reproduce the code, there may be some fluctuations, and the maximum miou is equal to 73.1%. I saw that you reproduced the same result. Could you please add your contact information and provide me with some information about your training so that I can better reproduce the code? thank you. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


I hope you can reply to my email amidst your busy schedule. I really need your help. Thank you again, my email is 1924487356@qq.com

**Comment by anizyu** [comment] 2023-05-30 02:30
怎么修改可视化结果的颜色和原始标签一样的？
有代码可以提供吗？

**Comment by CoinCheung** [comment] 2023-08-07 10:44
I am closing this, because the problem is likely to be solved now.

**Closed by CoinCheung** 2023-08-07 10:44 UTC
