### ISSUE TITLE
AttributeError: module ' lib ' has no attribute ' data '

### ISSUE THREAD

**Issue by fancyhhhhhh** [CoinCheung/BiSeNet#283] opened 2022-12-08 07:58 UTC
Hi , brother ,I am coming again ,hhh
Now I am going to deploy this model in a margin device(just like the NVIDIA jetson nx)
The margin devices , which cpu is arm64 
my platform is like ubuntu 18.04 cuda 10.2 cudnn 8 ,NO independent GPU 
**and my pytorch is 1.8.0 ,opencv is 3 . 4 . 15 .55(which is the lowest version for aarch64 I found)**
and my question is like this ,I downloaded the model and weight you posted , and try to get started
but I got problem like this
![99dad76903115f9fb91d3f7b0f77d2f](https://user-images.githubusercontent.com/116441063/206390547-7dc1367d-4429-496d-b664-e00d01fd5fda.jpg)

**Comment by fancyhhhhhh** [comment] 2022-12-08 07:59
I guess the reason is that the version of pytorch is uncompatiable with the opencv-python

**Comment by CoinCheung** [comment] 2022-12-08 08:08
HI, what is your python version? I use python3.8.12.

**Comment by fancyhhhhhh** [comment] 2022-12-08 08:16
> HI, what is your python version? I use python3.8.12.

My python is 3.6.15

**Comment by fancyhhhhhh** [comment] 2022-12-08 08:22
At first , I tried to install pytorch v1.11 , but it's to high for nvidia jetson ,and I got some problem due to the version is too high
So I uninstall pytorch 1.11 , and then I install v1.8.0
may be you could look this
![bf3f17107e19d5356652feada026e80](https://user-images.githubusercontent.com/116441063/206395698-3447d096-555d-4a68-a3f0-42b322d7716c.png)

**Comment by fancyhhhhhh** [comment] 2022-12-08 08:39
> Did you ever try to use python3.8 instead of python3.6?

No , I haven't try to use python3.8 instead of python 3.6
The version of cuda embbed in nvidia jetson is 10.2 ,and I installed pytorch v1.11.0 **(which the version of python is 3.8)** at first , I got FALSE when I run the command _torch.cuda.is_available()_
After referring some blogs , I think it's the version of my pytorch is too high
so I installed the v1.8.0

So you mean I had better install pytorch v1.11 ?
Thanks for your replying

**Comment by CoinCheung** [comment] 2022-12-08 09:05
Can you try to add two lines
```
import sys
sys.path.insert(0, '.')
```
at this line?
https://github.com/CoinCheung/BiSeNet/blob/e81fb128e131d3eb4ce28c4887fc18e5dbc329a5/lib/data/get_dataloader.py#L5

**Comment by fancyhhhhhh** [comment] 2022-12-08 10:38
Thank you ,but the result is the same
![7adce6ee391f6991dc0c09f3cb56c01](https://user-images.githubusercontent.com/116441063/206425681-2dab9ff3-e50b-4cc2-b035-cfcc2f818ba6.png)

**Comment by fancyhhhhhh** [comment] 2022-12-08 14:31
Hi , I think ,the problem is because the version of my python
I installed pytorch v1.10.0 (the version of python is still 3.6) just now ,and I got the error message like above
Because my JetPack is 4. 5 , which supports the latest version of pytorch is 1.10.0
So tomorrow I am going to update my JetPack , Thank you  so much for your help ,really appreciate  it

**Comment by CoinCheung** [comment] 2022-12-09 03:28
Would you print out the result of this at the above line:
```
import sys
sys.path.insert(0, '.')
print(sys.path)
```

**Comment by fancyhhhhhh** [comment] 2022-12-12 14:48
Sorry for replying to your message so late.
I had some  troubles to deal with in the past few days . I ‘m sorry.
Now I 'm installing opencv-python in the margin device ,it's really slow.
Once I got the result of "print(sys.path)" , I will make contact with you .Really appreciate it.
And my new question is ,if I want to change the color of the identified objects , where do I need to change?
Sorry to take your time .

**Comment by fancyhhhhhh** [comment] 2022-12-12 14:53
> Sorry for replying to your message so late. I had some troubles to deal with in the past few days . I ‘m sorry. Now I 'm installing opencv-python in the margin device ,it's really slow. Once I got the result of "print(sys.path)" , I will make contact with you .Really appreciate it. And my new question is ,if I want to change the color of the identified objects , where do I need to change? Sorry to take your time .

Actually, I want to change the color of background to transparent  . So that I can make sure that the  background can be recognized easily.
Thank you very much.

**Comment by ionia1999** [comment] 2023-03-31 09:05
just change "import lib.data.transform_cv2 as T" into "from lib.data import transform_cv2 as T"

**Comment by bonne658** [comment] 2023-06-08 06:13
> just change "import lib.data.transform_cv2 as T" into "from lib.data import transform_cv2 as T"

I solve the problem using this.

**Comment by CoinCheung** [comment] 2023-08-07 10:40
Glad to know the problem is solved, I am closing this.

**Closed by CoinCheung** 2023-08-07 10:40 UTC
